version : '3'

services:
    mysql:
      image: mysql/mysql-server:8.0
      environment:
        - MYSQL_ROOT_PASSWORD=1199
        - MYSQL_DATABASE=ememo_test
        - MYSQL_USER=root
        - MYSQL_PASSWORD=1199
        - TZ=Asia/Ho_Chi_Minh
      ports:
        - "3336:3306"
      volumes:
        - mysql-data:/var/lib/mysql
        - ./new.sql:/docker-entrypoint-initdb.d/init.sql
    web:
      image: duongtai264/ememo_kai:0.0.7
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://192.168.1.19:3336/ememo_test?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&character_set_server=utf8mb4
      depends_on:
        - mysql
volumes:
  mysql-data: