spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ememo_test?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&character_set_server=utf8mb4
    username: root
    password: 11991199
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
upload:
  path: uploads/images/


#  mail:
#    host: your-smtp-host
#    port: your-smtp-port
#    username: your-email-username
#    password: your-email-password
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#      smtp:
#        auth: true

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 513834690318-u46pnct4463o8cgfiurcbcaf88ud0uuc.apps.googleusercontent.com
#            client-secret: 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
#          facebook:
#            client-id: 1301829553806838
#            client-secret: a5cbf1f459d9a999761d358c9cef1bf5
app:
  client:
    url: http://localhost:4200/*
